//redux types keys
//jordan data
export const GET_JORDAN_DATA_REQUESTED = 'GET_JORDAN_DATA_REQUESTED';
export const GET_JORDAN_DATA_SUCCESS = 'GET_JORDAN_DATA_SUCCESS';
export const GET_JORDAN_DATA_FAILED = 'GET_JORDAN_DATA_FAILED';

//kobe data
export const GET_KOBE_DATA_REQUESTED = 'GET_KOBE_DATA_REQUESTED';
export const GET_KOBE_DATA_SUCCESS = 'GET_KOBE_DATA_SUCCESS';
export const GET_KOBE_DATA_FAILED = 'GET_KOBE_DATA_FAILED';

//lebron data
export const GET_LEBRON_DATA_REQUESTED = 'GET_LEBRON_DATA_REQUESTED';
export const GET_LEBRON_DATA_SUCCESS = 'GET_LEBRON_DATA_SUCCESS';
export const GET_LEBRON_DATA_FAILED = 'GET_LEBRON_DATA_FAILED';